In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from collections import Counter
from itertools import combinations
import seaborn as sns
warnings.filterwarnings("ignore")

In [2]:
# Load data
df = pd.read_csv("train.csv")

## Per Model

In [3]:
df_model_price_variations = (
    df.groupby("modelId", as_index=False)
      .agg(
          prices=("price", lambda x: sorted(x.unique())),
          unique_price_count=("price", "nunique"),
      )
      .sort_values("unique_price_count", ascending=False)
      .reset_index(drop=True)
)

In [4]:
df_model_price_variations.head(4)

,modelId,prices,unique_price_count
0,225798114762,"[15900000, 19000000, 19300000, 19900000, 20500...",5
1,240069696046,"[4200000, 5500000, 11800000, 12000000]",4
2,237155424280,"[53000000, 53500000, 55000000, 58000000]",4
3,237155424279,"[27500000, 28000000, 29500000, 32500000]",4

In [5]:
df_single_price_model = (
    df_model_price_variations[
        df_model_price_variations["unique_price_count"] == 1
    ]
    .reset_index(drop=True)
)

In [6]:
df_single_price_model.head(4)

        modelId      prices  unique_price_count
0  204649166356  [52000000]                   1
1  242896977045  [85000000]                   1
2  204649166354  [30000000]                   1
3  204649166353  [52000000]                   1

In [7]:
df_multiple_price_model = (
    df_model_price_variations[
        df_model_price_variations["unique_price_count"] > 1
    ]
    .reset_index(drop=True)
)

In [8]:
df_multiple_price_model.head(4)

,modelId,prices,unique_price_count
0,225798114762,"[15900000, 19000000, 19300000, 19900000, 20500...",5
1,240069696046,"[4200000, 5500000, 11800000, 12000000]",4
2,237155424280,"[53000000, 53500000, 55000000, 58000000]",4
3,237155424279,"[27500000, 28000000, 29500000, 32500000]",4

In [9]:
model_ids_single_price = df_single_price_model["modelId"].tolist()
model_ids_multiple_price = df_multiple_price_model["modelId"].tolist()

In [10]:
len(model_ids_single_price)

5253

In [11]:
len(model_ids_multiple_price)

1033

In [12]:
df_single_price = (
    df[df["modelId"].isin(model_ids_single_price)]
    .reset_index(drop=True)
)

In [13]:
df_single_price.head(4)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
0,2025-01-02 01:45:48.634,1006671485,18087284916,166287259494,16900000,0,0,100013,NaN,NaN,...,14900000,5.0,1,1,4.936441,70.0,3955,t,f,f
1,2025-01-02 01:45:48.634,1006671485,18087284916,166287259497,11900000,13900000,474465164066816,100013,NaN,NaN,...,14900000,5.0,1,1,4.936441,70.0,3955,t,f,f
2,2025-01-02 01:45:48.634,1006671485,18087284916,166287259492,16900000,0,0,100013,NaN,NaN,...,14900000,5.0,1,1,4.936441,70.0,3955,t,f,f
3,2025-01-02 01:45:48.634,1006671485,18087284916,166287259490,16900000,0,0,100013,NaN,NaN,...,14900000,5.0,1,1,4.936441,70.0,3955,t,f,f

In [14]:
df_multiple_price = (
    df[df["modelId"].isin(model_ids_multiple_price)]
    .reset_index(drop=True)
)

In [15]:
df_multiple_price.head(4)

,capturedAt,shopId,itemId,modelId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
0,2025-01-01 22:37:36.424,1008004,29302587134,185168612932,41900000,68000000,534463751667712,100630,NaN,NaN,...,41900000,0.000000,0,0,4.975239,55.0,158,f,f,f
1,2025-01-02 06:37:16.329,1007168904,23280684426,225645764832,11000000,15800000,477339923251200,100636,NaN,NaN,...,28000000,5.000000,16,14,4.963365,57.0,486,f,f,f
2,2025-01-02 06:37:19.901,1001936601,25853136753,49730769220,7000000,9900000,449920113836032,100001,NaN,NaN,...,7000000,0.000000,0,0,4.948843,100.0,844,f,t,f
3,2025-01-02 07:31:38.137,1009757562,23890302178,168366195565,27900000,0,0,100001,NaN,NaN,...,34900000,4.970037,267,237,4.974790,97.0,3060,f,t,f

In [16]:
df_single_price_feature_variations = (
    df_single_price
    .drop(columns=["capturedAt"])
    .groupby("modelId")
    .nunique()
    .reset_index()
)

In [17]:
df_single_price_feature_variations.head(4)

,modelId,shopId,itemId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,raw_discount,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
0,52465307,1,1,1,1,1,1,0,0,1,...,1,1,1,1,34,10,18,1,1,1
1,52465308,1,1,1,1,1,1,0,0,1,...,1,1,1,1,34,10,18,1,1,1
2,52465309,1,1,1,1,1,1,0,0,1,...,1,1,1,1,34,10,18,1,1,1
3,52465310,1,1,1,1,1,1,0,0,1,...,1,1,1,1,34,10,18,1,1,1

In [18]:
df_multiple_price_feature_variations = (
    df_multiple_price
    .drop(columns=["capturedAt"])
    .groupby("modelId")
    .nunique()
    .reset_index()
)

In [19]:
df_multiple_price_feature_variations.head(4)

,modelId,shopId,itemId,price,priceBeforeDiscount,promotionId,cat_id,stock,normal_stock,raw_discount,...,item_price_max,review_rating,total_rating_count,cmt_count,shop_rating,shop_response_rate,shop_follower_count,is_official_shop,is_verified,is_preferred_plus_seller
0,56064071,1,1,2,1,1,1,0,0,1,...,2,1,1,1,26,13,14,1,1,1
1,173099958,1,1,2,1,1,1,0,0,1,...,2,1,1,1,20,9,7,1,1,1
2,176064773,1,1,2,1,1,1,0,0,1,...,2,2,2,2,10,4,4,1,1,1
3,182005603,1,1,2,1,1,1,0,0,1,...,2,1,1,1,9,2,4,1,1,1

In [20]:
df_multiple_price_feature_variations.drop(columns=["modelId"]).std()

shopId                       0.000000
itemId                       0.000000
price                        0.460986
priceBeforeDiscount          0.524721
promotionId                  4.696164
cat_id                       0.150717
stock                        0.239423
normal_stock                 0.239423
raw_discount                 0.760908
show_discount                0.760908
brand                        0.470128
is_free_shipping             0.000000
is_pre_order                 0.241191
item_price_min               0.697834
item_price_max               0.666637
review_rating               14.114012
total_rating_count          14.248765
cmt_count                   14.217336
shop_rating                 26.305487
shop_response_rate           5.170368
shop_follower_count         14.480798
is_official_shop             0.000000
is_verified                  0.386027
is_preferred_plus_seller     0.000000
dtype: float64

In [21]:
df_single_price_feature_variations.drop(columns=["modelId"]).std()

shopId                       0.000000
itemId                       0.000000
price                        0.000000
priceBeforeDiscount          0.053366
promotionId                  0.697719
cat_id                       0.013797
stock                        0.191392
normal_stock                 0.191392
raw_discount                 0.206226
show_discount                0.206226
brand                        0.452860
is_free_shipping             0.000000
is_pre_order                 0.148811
item_price_min               0.286423
item_price_max               0.287800
review_rating                7.671746
total_rating_count           7.773190
cmt_count                    7.771093
shop_rating                 24.025033
shop_response_rate           5.229997
shop_follower_count         14.655071
is_official_shop             0.000000
is_verified                  0.408140
is_preferred_plus_seller     0.000000
dtype: float64