In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
from collections import Counter
from itertools import combinations
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
warnings.filterwarnings("ignore")

In [2]:
# Load data
df = pd.read_csv("train.csv")

In [3]:
# normalize price
df["price"] = df["price"] / 100_000
df["item_price_min"] = df["item_price_min"] / 100_000
df["item_price_max"] = df["item_price_max"] / 100_000

In [4]:
keep_columns = [
    "price",
    "item_price_min",
    "item_price_max",
]

df = (
    df[keep_columns]
    .drop_duplicates(keep="first")
    .copy()
)

df["diff_min"] = df["price"] - df["item_price_min"]
df["diff_max"] = df["item_price_max"] - df["price"]

df["diff_min_pct"] = df["diff_min"] / df["price"]
df["diff_max_pct"] = df["diff_max"] / df["price"]

In [5]:
df

,price,item_price_min,item_price_max,diff_min,diff_max,diff_min_pct,diff_max_pct
0,419.0,419.0,419.0,0.0,0.0,0.000000,0.000000
1,169.0,119.0,149.0,50.0,-20.0,0.295858,-0.118343
2,119.0,119.0,149.0,0.0,30.0,0.000000,0.252101
7,149.0,119.0,149.0,30.0,0.0,0.201342,0.000000
10,390.0,390.0,390.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...
300886,990.0,198.0,890.0,792.0,-100.0,0.800000,-0.101010
300887,220.0,198.0,890.0,22.0,670.0,0.100000,3.045455
300889,450.0,198.0,890.0,252.0,440.0,0.560000,0.977778
300890,290.0,198.0,890.0,92.0,600.0,0.317241,2.068966
300891,309.0,265.0,265.0,44.0,-44.0,0.142395,-0.142395

In [6]:
df["diff_max"].min(), df["diff_max"].max()

(-4000.0, 4490.0)

In [7]:
df["diff_max_pct"].min(), df["diff_max_pct"].max()

(-0.7997997997997998, 6.4363636363636365)

In [8]:
df["diff_min"].min(), df["diff_min"].max()

(-861.0, 4490.0)

In [9]:
df["diff_min_pct"].min(), df["diff_min_pct"].max()

(-2.4482758620689653, 0.8687350835322196)

In [10]:
df_diff= df[
    (df["diff_min_pct"] < -0.6) |
    (df["diff_max_pct"] < -0.6)
].copy()

In [11]:
df_diff

,price,item_price_min,item_price_max,diff_min,diff_max,diff_min_pct,diff_max_pct
68,499.0,139.0,139.0,360.0,-360.0,0.721443,-0.721443
588,139.0,52.0,52.0,87.0,-87.0,0.625899,-0.625899
681,490.0,138.0,138.0,352.0,-352.0,0.718367,-0.718367
1000,1280.0,299.0,399.0,981.0,-881.0,0.766406,-0.688281
1179,2970.0,990.0,990.0,1980.0,-1980.0,0.666667,-0.666667
1282,8.0,3.0,3.0,5.0,-5.0,0.625000,-0.625000
1453,680.0,239.0,259.0,441.0,-421.0,0.648529,-0.619118
2323,280.0,99.0,99.0,181.0,-181.0,0.646429,-0.646429
3613,58.0,119.0,119.0,-61.0,61.0,-1.051724,1.051724
4274,999.0,200.0,200.0,799.0,-799.0,0.799800,-0.799800
8285,450.0,129.0,129.0,321.0,-321.0,0.713333,-0.713333
9194,588.0,210.0,215.0,378.0,-373.0,0.642857,-0.634354
10949,3540.0,990.0,990.0,2550.0,-2550.0,0.720339,-0.720339
10964,420.0,820.0,1080.0,-400.0,660.0,-0.952381,1.571429
11016,90.0,230.0,230.0,-140.0,140.0,-1.555556,1.555556
11660,50.0,14.0,16.0,36.0,-34.0,0.720000,-0.680000
12969,99.0,169.0,169.0,-70.0,70.0,-0.707071,0.707071
13977,3.0,5.0,5.0,-2.0,2.0,-0.666667,0.666667
15220,59.0,135.0,135.0,-76.0,76.0,-1.288136,1.288136
16929,50.0,14.0,15.0,36.0,-35.0,0.720000,-0.700000
18135,999.0,250.0,250.0,749.0,-749.0,0.749750,-0.749750
24115,649.0,1499.0,2399.0,-850.0,1750.0,-1.309707,2.696456
24120,638.0,1499.0,2399.0,-861.0,1761.0,-1.349530,2.760188
25575,139.0,340.0,340.0,-201.0,201.0,-1.446043,1.446043
25577,200.0,340.0,340.0,-140.0,140.0,-0.700000,0.700000
25578,100.0,340.0,340.0,-240.0,240.0,-2.400000,2.400000
26697,199.0,399.0,399.0,-200.0,200.0,-1.005025,1.005025
27853,480.0,165.0,165.0,315.0,-315.0,0.656250,-0.656250
43200,169.0,49.0,49.0,120.0,-120.0,0.710059,-0.710059
44772,79.0,129.0,179.0,-50.0,100.0,-0.632911,1.265823
45204,120.0,38.0,38.0,82.0,-82.0,0.683333,-0.683333
47056,480.0,129.0,158.0,351.0,-322.0,0.731250,-0.670833
58412,95.0,19.0,30.0,76.0,-65.0,0.800000,-0.684211
59619,1290.0,499.0,499.0,791.0,-791.0,0.613178,-0.613178
63513,169.0,45.0,65.0,124.0,-104.0,0.733728,-0.615385
88670,390.0,793.0,793.0,-403.0,403.0,-1.033333,1.033333
107683,29.0,100.0,100.0,-71.0,71.0,-2.448276,2.448276
109083,10.0,20.0,40.0,-10.0,30.0,-1.000000,3.000000
112727,79.0,129.0,129.0,-50.0,50.0,-0.632911,0.632911
119967,695.0,205.0,205.0,490.0,-490.0,0.705036,-0.705036
133945,480.0,128.0,158.0,352.0,-322.0,0.733333,-0.670833
157743,69.0,119.0,119.0,-50.0,50.0,-0.724638,0.724638
237615,480.0,99.0,158.0,381.0,-322.0,0.793750,-0.670833
238824,3380.0,799.0,799.0,2581.0,-2581.0,0.763609,-0.763609
238825,3539.0,799.0,799.0,2740.0,-2740.0,0.774230,-0.774230
238826,3900.0,799.0,799.0,3101.0,-3101.0,0.795128,-0.795128
238828,3690.0,799.0,799.0,2891.0,-2891.0,0.783469,-0.783469
250374,330.0,880.0,880.0,-550.0,550.0,-1.666667,1.666667
263611,300.0,510.0,520.0,-210.0,220.0,-0.700000,0.733333
267592,169.0,45.0,45.0,124.0,-124.0,0.733728,-0.733728
277729,219.0,669.0,669.0,-450.0,450.0,-2.054795,2.054795